name: Build and Release Binary

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      TARGET: x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Linux Binary
        run: |
          rustup target add $TARGET
          cargo build --release --target $TARGET --locked

      - name: Create Release Directory
        run: mkdir -p release
        working-directory: ${{ github.workspace }}

      - name: Archive Linux Binary
        run: cp target/$TARGET/release/creator release/
        working-directory: ${{ github.workspace }}

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-release-${{ env.TARGET }}
          path: release

  build-macos:
    env:
      TARGET: x86_64-apple-darwin
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build macOS Binary
        run: |
          cargo build --release --target $TARGET --locked
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.7

      - name: Create Release Directory
        run: mkdir -p release
        working-directory: ${{ github.workspace }}

      - name: Archive macOS Binary
        run: cp target/$TARGET/release/creator release/
        working-directory: ${{ github.workspace }}

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-release-${{ env.TARGET }}
          path: release
